make_image:
  stage: build
  script:
    - git fetch
    - git checkout $CI_COMMIT_REF_NAME
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    - git clean -xfd
    - time docker build . --no-cache -t gippy:$CI_COMMIT_REF_SLUG
  tags:
    - gipsdev
  after_script:
   - docker system prune -f


run_tests:
  stage: test
  script:
    - docker run --rm gippy:$CI_COMMIT_REF_SLUG pytest --cov gippy
  tags:
    - gipsdev
  after_script:
    - docker image rm gippy:$CI_COMMIT_REF_SLUG
    - docker system prune -f
