twenty_oh_four:
  stage: build
  script:
    - git fetch
    - git checkout $CI_COMMIT_REF_NAME
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    - git clean -xfd
    - time docker build .
      --no-cache
      -t gippy:tof-$CI_COMMIT_REF_SLUG
  tags:
    - gipsdev
  after_script:
   - docker system prune -f

twenty_oh_four_ubuntugis:
  stage: build
  script:
    - git fetch
    - git checkout $CI_COMMIT_REF_NAME
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    - git clean -xfd
    - time docker build .
      --no-cache
      --build-arg UBUNTUGIS_PPA="ppa:ubuntugis/ubuntugis-unstable"
      -t gippy:tof-ugu-$CI_COMMIT_REF_SLUG
  tags:
    - gipsdev
  # only:
  #   - develop
  after_script:
   - docker system prune -f

eighteen_oh_four_ubuntugis:
  stage: build
  script:
    - git fetch
    - git checkout $CI_COMMIT_REF_NAME
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    - git clean -xfd
    - time docker build .
      --build-arg BASE_IMAGE="ubuntu:18.04"
      --build-arg UBUNTUGIS_PPA="ppa:ubuntugis/ppa"
      --no-cache
      -t gippy:eof-ugs-$CI_COMMIT_REF_SLUG
  tags:
    - gipsdev
  # only:
  #   - develop
  after_script:
   - docker system prune -f

eighteen_oh_four_unstable:
  stage: build
  script:
    - git fetch
    - git checkout $CI_COMMIT_REF_NAME
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    - git clean -xfd
    - time docker build .
      --build-arg BASE_IMAGE="ubuntu:18.04"
      --build-arg UBUNTUGIS_PPA="ppa:ubuntugis/ubuntugis-unstable"
      --no-cache
      -t gippy:eof-ugu-$CI_COMMIT_REF_SLUG
  tags:
    - gipsdev
  # only:
  #   - develop
  after_script:
   - docker system prune -f

sixteen_oh_four:
  stage: build
  script:
    - git fetch
    - git checkout $CI_COMMIT_REF_NAME
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    - git clean -xfd
    - time docker build .
      --build-arg BASE_IMAGE="ubuntu:16.04"
      --build-arg UBUNTUGIS_PPA="FALSE"
      --no-cache
      -t gippy:sof-$CI_COMMIT_REF_SLUG
  tags:
    - gipsdev
  # only:
  #   - develop
  after_script:
   - docker system prune -f


sixteen_oh_four_ubuntugis:
  stage: build
  script:
    - git fetch
    - git checkout $CI_COMMIT_REF_NAME
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    - git clean -xfd
    - time docker build .
      --build-arg BASE_IMAGE="ubuntu:16.04"
      --build-arg UBUNTUGIS_PPA="ppa:ubuntugis/ubuntugis-unstable"
      --no-cache
      -t gippy:sof-ugu-$CI_COMMIT_REF_SLUG
  tags:
    - gipsdev
  # only:
  #   - develop
  after_script:
   - docker system prune -f


tof_tests:
  stage: test
  needs:
    - twenty_oh_four
  script:
    - docker run --workdir /build/test
      -v ${PWD}:/backdoor
      --rm gippy:tof-$CI_COMMIT_REF_SLUG
      pytest --cov gippy
      --junit-xml=/backdoor/tof-$CI_COMMIT_REF_SLUG.xml
  tags:
    - gipsdev
  artifacts:
    reports:
      junit: tof-$CI_COMMIT_REF_SLUG.xml
  after_script:
    - docker image rm gippy:tof-$CI_COMMIT_REF_SLUG


tof_ugu_tests:
  stage: test
  needs:
    - twenty_oh_four_ubuntugis
  script:
    - docker run --workdir /build/test
      -v ${PWD}:/backdoor
      --rm gippy:tof-ugu-$CI_COMMIT_REF_SLUG
      pytest --cov gippy
      --junit-xml=/backdoor/tof-ugu-$CI_COMMIT_REF_SLUG.xml
  tags:
    - gipsdev
  artifacts:
    reports:
      junit: tof-ugu-$CI_COMMIT_REF_SLUG.xml
  after_script:
    - docker image rm gippy:tof-ugu-$CI_COMMIT_REF_SLUG

eof_ugs_tests:
  stage: test
  needs:
    - eighteen_oh_four_ubuntugis
  script:
    - docker run --workdir /build/test
      -v ${PWD}:/backdoor
      --rm gippy:eof-ugs-$CI_COMMIT_REF_SLUG
      pytest --cov gippy
      --junit-xml=/backdoor/eof-ugs-$CI_COMMIT_REF_SLUG.xml
  tags:
    - gipsdev
  artifacts:
    reports:
      junit: eof-ugs-$CI_COMMIT_REF_SLUG.xml
  after_script:
    - docker image rm gippy:eof-ugs-$CI_COMMIT_REF_SLUG


eof_ugu_tests:
  stage: test
  needs:
    - eighteen_oh_four_unstable
  script:
    - docker run --workdir /build/test
      -v ${PWD}:/backdoor
      --rm gippy:eof-ugu-$CI_COMMIT_REF_SLUG
      pytest --cov gippy
      --junit-xml=/backdoor/eof-ugu-$CI_COMMIT_REF_SLUG.xml
  tags:
    - gipsdev
  artifacts:
    reports:
      junit: eof-ugu-$CI_COMMIT_REF_SLUG.xml
  after_script:
    - docker image rm gippy:eof-ugu-$CI_COMMIT_REF_SLUG

sof_tests:
  stage: test
  needs:
    - sixteen_oh_four
  script:
    - docker run --workdir /build/test
      -v ${PWD}:/backdoor
      --rm gippy:sof-$CI_COMMIT_REF_SLUG
      pytest --cov gippy
      --junit-xml=/backdoor/sof-$CI_COMMIT_REF_SLUG.xml
  tags:
    - gipsdev
  artifacts:
    reports:
      junit: sof-$CI_COMMIT_REF_SLUG.xml
  after_script:
    - docker image rm gippy:sof-$CI_COMMIT_REF_SLUG

sof_ugu_tests:
  stage: test
  needs:
    - sixteen_oh_four_ubuntugis
  script:
    - docker run --workdir /build/test
      -v ${PWD}:/backdoor
      --rm gippy:sof-ugu-$CI_COMMIT_REF_SLUG
      pytest --cov gippy
      --junit-xml=/backdoor/sof-ugu-$CI_COMMIT_REF_SLUG.xml
  tags:
    - gipsdev
  artifacts:
    reports:
      junit: sof-ugu-$CI_COMMIT_REF_SLUG.xml
  after_script:
    - docker image rm gippy:sof-ugu-$CI_COMMIT_REF_SLUG

