version: '2'
  
services:

  base:
    build:
      context: .
    image: 'gippy:latest'
    entrypoint: /bin/bash
    volumes:
      - '.:/home/geolambda/work'

  test36:
    image: 'gippy:latest'
    entrypoint: bash -c 'python3 -m pytest -v'
    working_dir: /home/geolambda/test
    volumes:
      - './test:/home/geolambda/test'
